wandb_version: 1

ES:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    code_path: code/gfml-rs/codes/main.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1688056738.411017
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.12
      5: 0.13.4
      8:
      - 5
a_fold:
  desc: null
  value: 100
bpr_batch:
  desc: null
  value: 2048
clip_norm:
  desc: null
  value: 1
comment:
  desc: null
  value: lgn
cov_loss_weight:
  desc: null
  value: 1.0
dataset:
  desc: null
  value: ml1m
decay:
  desc: null
  value: 0.0001
dist_mode:
  desc: null
  value: l2
dropout:
  desc: null
  value: 0
dropout_rate:
  desc: null
  value: 0.2
ema_on:
  desc: null
  value: 1
emb_norm:
  desc: null
  value: 1
epochs:
  desc: null
  value: 1000
exp_name:
  desc: null
  value: Apple
feature_l2_reg:
  desc: null
  value: 0.1
feature_projection_scaling_factor:
  desc: null
  value: 0.5
features:
  desc: null
  value: null
gpu_id:
  desc: null
  value: 1
hidden_layer_dim:
  desc: null
  value: 64
infer_mode:
  desc: null
  value: mat
keepprob:
  desc: null
  value: 0.6
lam_d:
  desc: null
  value: 0.995
lamb:
  desc: null
  value: 2.0
layer:
  desc: null
  value: 3
load:
  desc: null
  value: 0
loss_mode:
  desc: null
  value: mix_bpr
lr:
  desc: null
  value: 0.0004
lr_decay:
  desc: null
  value: 0.01
margin:
  desc: null
  value: 1.9
mass_mode:
  desc: null
  value: both
master_learning_rate:
  desc: null
  value: 0.1
mix_ratio:
  desc: null
  value: 0.4
model:
  desc: null
  value: cml
multicore:
  desc: null
  value: 0
path:
  desc: null
  value: ./checkpoints
pretrain:
  desc: null
  value: 0
recdim:
  desc: null
  value: 64
seed:
  desc: null
  value: 2020
tensorboard:
  desc: null
  value: 0
testbatch:
  desc: null
  value: 100
topks:
  desc: null
  value: '[5, 10, 20]'
use_cov_loss:
  desc: null
  value: false
use_rank_weight:
  desc: null
  value: true
weight_decay:
  desc: null
  value: 0.0003
