wandb_version: 1

ES:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    code_path: code/gfml-rs/codes/main.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1688053141.726656
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 1
      - 13
      - 16
      - 23
      4: 3.9.12
      5: 0.13.4
      8:
      - 5
a_fold:
  desc: null
  value: 100
bpr_batch:
  desc: null
  value: 2048
comment:
  desc: null
  value: lgn
dataset:
  desc: null
  value: ml1m
decay:
  desc: null
  value: 0.004033682136567116
dist_mode:
  desc: null
  value: l2
dropout:
  desc: null
  value: 0
ema_on:
  desc: null
  value: 1
emb_norm:
  desc: null
  value: 1
epochs:
  desc: null
  value: 1000
exp_name:
  desc: null
  value: Apple
gpu_id:
  desc: null
  value: 3
infer_mode:
  desc: null
  value: mat
keepprob:
  desc: null
  value: 0.6
lam_d:
  desc: null
  value: 0.995
lamb:
  desc: null
  value: 3.0824860422368356
layer:
  desc: null
  value: 3
load:
  desc: null
  value: 0
loss_mode:
  desc: null
  value: mix_bpr
lr:
  desc: null
  value: 0.0005623164777448317
lr_decay:
  desc: null
  value: 0.01
mass_mode:
  desc: null
  value: both
mix_ratio:
  desc: null
  value: 0.2
model:
  desc: null
  value: mf
multicore:
  desc: null
  value: 0
path:
  desc: null
  value: ./checkpoints
pretrain:
  desc: null
  value: 0
recdim:
  desc: null
  value: 64
seed:
  desc: null
  value: 2020
tensorboard:
  desc: null
  value: 0
testbatch:
  desc: null
  value: 100
topks:
  desc: null
  value: '[5, 10, 20]'
weight_decay:
  desc: null
  value: 0.08764474435122023
