import argparse

def parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument("--api-key", type=str, help="API Key for Comet.ml")
    parser.add_argument("--dataset", default="c10", type=str, help="[c10, c100, svhn]")
    parser.add_argument("--num-classes", default=10, type=int)
    parser.add_argument("--model-name", default="vit_gra", help="[vit, vit_gra]", type=str)
    parser.add_argument("--patch", default=8, type=int)
    parser.add_argument("--batch-size", default=128, type=int)
    parser.add_argument("--eval-batch-size", default=1024, type=int)
    parser.add_argument("--lr", default=1e-3, type=float)
    parser.add_argument("--min-lr", default=1e-5, type=float)
    parser.add_argument("--beta1", default=0.9, type=float)
    parser.add_argument("--beta2", default=0.999, type=float)
    parser.add_argument("--off-benchmark", action="store_true")
    parser.add_argument("--max-epochs", default=200, type=int)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--weight-decay", default=5e-5, type=float)
    parser.add_argument("--warmup-epoch", default=5, type=int)
    parser.add_argument("--precision", default=16, type=int)
    parser.add_argument("--autoaugment", action="store_true")
    parser.add_argument("--criterion", default="ce")
    parser.add_argument("--label-smoothing", action="store_true")
    parser.add_argument("--smoothing", default=0.1, type=float)
    parser.add_argument("--rcpaste", action="store_true")
    parser.add_argument("--cutmix", action="store_true")
    parser.add_argument("--mixup", action="store_true")
    parser.add_argument("--dropout", default=0.0, type=float)
    parser.add_argument("--head", default=12, type=int)
    parser.add_argument("--num-layers", default=7, type=int)
    parser.add_argument("--hidden", default=384, type=int)
    parser.add_argument("--mlp-hidden", default=384, type=int)
    parser.add_argument("--off-cls-token", action="store_true")
    parser.add_argument("--seed", default=42, type=int)
    parser.add_argument("--project-name", default="vit-gravity",
                        help="[vit-gra-imb-c10, vit-gra-imb-c100, vit-gra-c10, vit-gra-c100]")
    parser.add_argument("--lamb_gra", type=float, default=1.0)
    parser.add_argument("--lamb_mix", type=float, default=0.5)
    parser.add_argument("--mix_on", type=int, default=0)
    parser.add_argument("--mix_mode", type=str, default='normal', help="[split, normal]")
    parser.add_argument("--score_norm", type=int, default=1)
    parser.add_argument("--dist_mode", type=str, default='l2', help="[l2, l1]")
    parser.add_argument("--mass_pos", type=str, default='full', help="[full, head, tail]")
    parser.add_argument("--num_split", type=int, default=6)
    parser.add_argument("--split_mix", type=int, default=0)
    return parser.parse_args()